openapi: 3.0.1
info:
  title: Products
  version: 0.1.0
servers:
- url: "{server}:{port}/products"
  variables:
    server:
      default: http://localhost
    port:
      default: httpPort
paths:
  /:
    get:
      operationId: operation_get
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: InternalServerError
    put:
      operationId: operation_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
    post:
      operationId: operation_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: Created
        "500":
          description: InternalServerError
  /{id}:
    get:
      operationId: "operation_get_/{id}"
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: NotFound
        "500":
          description: InternalServerError
    delete:
      operationId: "operation_delete_/{id}"
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
components:
  schemas:
    Product:
      required:
      - currency
      - price
      - productName
      type: object
      properties:
        id:
          type: integer
          format: int32
        productName:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
